<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-windows;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10</LangVersion>
		<RootNamespace>Example.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="Rhino.Testing" Version="9.0.7-beta" />
		<PackageReference Include="RhinoCommon" Version="9.0.26097.12305-wip" Private="False" PrivateAssets="all" ExcludeAssets="runtime" />
		<PackageReference Include="Grasshopper" Version="9.0.26097.12305-wip" Private="False" PrivateAssets="all" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Rhino.Testing.Configs.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Scripts\CircleArea.gh">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Scripts\" />
	</ItemGroup>

</Project>
